# Generated by Django 3.1.13 on 2021-10-30 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialClinico',
            fields=[
                ('numero_ficha', models.AutoField(primary_key=True, serialize=False, verbose_name='Número de Ficha')),
            ],
            options={
                'verbose_name': 'Historial Clinico',
                'verbose_name_plural': 'Historiales Clinicos',
                'db_table': 'HistorialClinico',
            },
        ),
    ]
