# Generated by Django 3.1.13 on 2022-08-11 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_historial_clinico', '0002_auto_20220806_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tratamientorealizado',
            name='id_historial_clinico',
        ),
    ]
