# Generated by Django 3.1.13 on 2022-08-11 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_historial_clinico', '0003_remove_tratamientorealizado_id_historial_clinico'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistorialClinico',
        ),
    ]
