# Generated by Django 3.1.13 on 2022-08-11 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_administrativo', '0052_remove_paciente_id_historial_clinico'),
        ('gestion_historial_clinico', '0006_historialclinico_paciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialclinico',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_administrativo.paciente', verbose_name='Id de historial clinico'),
        ),
    ]
