# Generated by Django 3.1.13 on 2022-08-13 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_historial_clinico', '0007_auto_20220810_2331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historialclinico',
            old_name='codigo_tratamiento',
            new_name='tratamiento',
        ),
    ]
