INSERT INTO public."Tratamiento"(nombre_tratamiento, descripcion_tratamiento,precio)
values
('LIMPIEZA DE SARROS','Este tratamiento es llamado tartrectomía o profilaxis dental. La palabra coloquial de este procedimiento es la higiene o limpieza dental',70000),
('ORTODONCIA', 'La ortodoncia es la rama de la odontología que se encarga de los problemas de los dientes y la mandíbula. La atención dental con ortodoncia incluye el uso de dispositivos, tales como los aparatos (frenos), para: Enderezar los dientes. Corregir problemas con la mordida. 
 Este tratamiento incluye: Radiografías, Limpieza de sarro, profilaxis, instalación de la aparotología arriba y abajo Mensualidad: 150000, con una entrega inicial de 700000',700000),
('CORONA DENTAL ACRÍLICO', 'Las coronas se usan para restaurar un diente dañado y devolverle su tamaño y forma normales. Pueden estar hechas de oro, otro metal, cerámica, o porcelana fundida a un metal. Si su corona se va a ver cuando usted sonríe, su dentista intentará igualarla al color de los dientes cercanos.',500000),
('CORONA DENTAL CEROMERO', 'Las coronas se usan para restaurar un diente dañado y devolverle su tamaño y forma normales. Pueden estar hechas de oro, otro metal, cerámica, o porcelana fundida a un metal. Si su corona se va a ver cuando usted sonríe, su dentista intentará igualarla al color de los dientes cercanos.',700000),
('CORONA DENTAL PORCELANA', 'Las coronas se usan para restaurar un diente dañado y devolverle su tamaño y forma normales. Pueden estar hechas de oro, otro metal, cerámica, o porcelana fundida a un metal. Si su corona se va a ver cuando usted sonríe, su dentista intentará igualarla al color de los dientes cercanos.',900000),
('PROTESIS REMOVIBLE ACRÍLICO', 'Son dentaduras mucosoportadas que reemplazan parte de los dientes. Se pueden realizar en acrílico rígido o semirígido. En caso de alergia al monómero se puede extraer o realizarse directamente con resina antialérgica. Los retenedores pueden ser : forjados , fundidos o estéticos.',650000),
('PROTESIS REMOVIBLE SUPERIOR E INFERIOR', 'Son dentaduras mucosoportadas que reemplazan parte de los dientes. Se pueden realizar en acrílico rígido o semirígido. En caso de alergia al monómero se puede extraer o realizarse directamente con resina antialérgica. Los retenedores pueden ser : forjados , fundidos o estéticos.\r\n\r\nPara este caso es el superior e inferior.',1100000),
('CARILLAS DENTALES CON RESINA', 'Las carillas de resina o composite son un tratamiento estético dental no invasivo, en el cual se aplica previo estudio, de forma manual – artística y con tecnología adhesiva sobre la cara vestibular de los dientes, finas láminas hechas a medida, con la finalidad de aportar las modificaciones estéticas y funcionales',300000),
('CARILLAS DENTALES CEROMERO', 'Ceramage es una microcerámica de silicato de circonio para restauraciones indirectas que tiene el mismo efecto de transmisión de la luz que los dientes naturales y produce una notable translucidez. Este compuesto se adhiere a una variedad de sustratos, incluyendo aleaciones de metales nobles y no nobles, y viene en una amplia gama de tonos para reproducir el color del diente natural y de las encías, además de en nuevos tonos de blanco.',500000),
('CARILLAS DENTALES PORCELANA',	'Se trata de una fina lámina de porcelana que se coloca en la parte visible del diente. Su funcionalidad es modificar el aspecto del diente en color, forma y brillo. Además, son resistentes y permiten comer con total normalidad.',	700000),
('ELIMINACIÓN DE SARRO MÁS PROFILAXIS',	'La profilaxis dental es el tratamiento por el cual se elimina la placa bacteriana adherida a las superficies dentales supra y yuxta gingival. Es una limpieza de carácter profesional que consigue eliminar la placa bacteriana de las zonas menos accesibles para el paciente.',200000),
('INACTIVACIÓN DE CARIES MÁS RESTAURACIÓN ESTÉTICA ANTERIORES',	'El procedimiento implica la remoción del tejido dentinario necrótico e infectado con instrumental de mano o rotatorio a baja velocidad, y la posterior restauración con aislamiento relativo con ionómeros vítreos convencionales o resinosos, o con derivados reforzados del óxido de cinc-eugeno',	150000),
('INACTIVACIÓN DE CARIES MÁS RESTAURACIÓN ESTÉTICA POSTERIORES',	'INACTIVACIÓN DE CARIES MÁS RESTAURACIÓN ESTÉTICA POSTERIORES CON PROTECCIÓN DE PULPA El procedimiento implica la remoción del tejido dentinario necrótico e infectado con instrumental de mano o rotatorio a baja velocidad, y la posterior restauración con aislamiento relativo con ionómeros vítreos convencionales o resinosos, o con derivados reforzados del óxido de cinc-eugeno', 200000),
('BLANQUEAMIENTO EN CLÍNICA',	'Blanqueamiento profesional en clínica es un tratamiento dental de activación por luz se realiza mediante una máquina de luz fría y peróxido de carbamida. El agente activador se encuentra en el peróxido de carbamida, y gracias a la luz fría se consigue que se liberen las propiedades blanqueadoras y penetren hasta el esmalte dental. La ventaja de este método es que el paciente solo tienen que acudir una vez a la clínica para realizar el tratamiento y verá el resultado final desde ese mismo día.',	700000),
('BLANQUEAMIENTO CON PLACA SUP. E INF',	'Este tipo de blanqueamiento dental requiere de unas placas de acrílico transparente que se amoldan a la forma de tus dientes y que servirán como recipiente del líquido de aclarado dental.',	400000),
('TRATAMIENTO DE CONDUCTO ANTERIORES',	'Es un procedimiento dental para salvar un diente al remover tejido nervioso muerto o en descomposición y bacterias del interior de un diente.',	400000),
('TRATAMIENTO DE CONDUCTO POSTERIORES',	'Es un procedimiento dental para salvar un diente al remover tejido nervioso muerto o en descomposición y bacterias del interior de un diente.',	600000),
('EXTRACCIÓN ANTERIORES',	'La extracción dental es el retiro de un diente de su cavidad alveolar del hueso maxilar o mandibular.',150000),
('EXTRACCIÓN POSTERIORES',	'La extracción dental es el retiro de un diente de su cavidad alveolar del hueso maxilar o mandibular.', 200000),
('EXTRACCIÓN ODONTOSECCIÓN',	'La odontosección consiste en seccionar el diente en distintos fragmentos para facilitar un tratamiento posterior, bien sea la restauración de un fragmento o pieza dental o su extracción, evitando que se fracturen las raíces, una complicación muy frecuente.',	250000),
('CONDUCTO', 'Es un procedimiento dental para salvar un diente al remover tejido nervioso muerto o en descomposición y bacterias del interior de un diente.',	100000)
