# Generated by Django 3.1.13 on 2022-07-07 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_tratamiento', '0006_delete_horario'),
        ('gestion_administrativo', '0044_auto_20220701_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='CobroContado',
            fields=[
                ('id_cobro_contado', models.AutoField(primary_key=True, serialize=False)),
                ('numero_documento', models.CharField(max_length=10, verbose_name='numero de documento')),
                ('razon_social', models.CharField(max_length=100, verbose_name='Nombre o razón social')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('monto_total', models.BigIntegerField()),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion_administrativo.paciente')),
            ],
            options={
                'verbose_name': 'Cobro al contado',
                'verbose_name_plural': 'Cobros al contado',
                'db_table': 'CobroContado',
            },
        ),
        migrations.CreateModel(
            name='DetalleCobroContado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cobro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_cobros.cobrocontado')),
            ],
            options={
                'verbose_name': 'Detalle de cobro al contado',
                'verbose_name_plural': 'Detalles de cobros al contado',
                'db_table': 'DetalleCobroContado',
            },
        ),
        migrations.CreateModel(
            name='DetalleCobroTratamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle_cobro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_cobros.detallecobrocontado')),
                ('tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_tratamiento.tratamiento')),
            ],
        ),
        migrations.AddField(
            model_name='detallecobrocontado',
            name='tratamientos',
            field=models.ManyToManyField(related_name='detalle_set', through='gestion_cobros.DetalleCobroTratamiento', to='gestion_tratamiento.Tratamiento'),
        ),
    ]
