# Generated by Django 3.1.13 on 2022-10-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cobros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobrocontado',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Confirmado', 'Confirmado')], default='Confirmado', max_length=10),
        ),
    ]
