# Generated by Django 3.1.13 on 2022-10-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cobros', '0002_cobrocontado_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobrocontado',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Confirmado', 'Confirmado')], default='Pendiente', max_length=10),
        ),
    ]
