# Generated by Django 3.1.13 on 2022-10-06 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cobros', '0003_auto_20221006_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cobrocontado',
            name='estado',
        ),
    ]
