# Generated by Django 3.1.13 on 2022-11-13 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cobros', '0004_remove_cobrocontado_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_factura', models.AutoField(primary_key=True, serialize=False)),
                ('sub_nro_factura1', models.CharField(max_length=3)),
                ('sub_nro_factura2', models.CharField(max_length=3)),
                ('sub_nro_factura3', models.IntegerField(max_length=7)),
                ('nro_factura', models.CharField(blank=True, max_length=60, null=True)),
                ('razon_social', models.CharField(blank=True, max_length=60, null=True, verbose_name='Nombre o Razón Social')),
                ('direccion', models.CharField(blank=True, max_length=80, null=True, verbose_name='Dirección')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('condicion_venta', models.CharField(choices=[('Contado', 'Contado'), ('Credito', 'Credito')], max_length=12, verbose_name='Condición de venta')),
                ('telefono', models.CharField(max_length=20)),
                ('total_pagar', models.IntegerField()),
                ('iva_5', models.FloatField()),
                ('iva_10', models.FloatField()),
                ('total_iva', models.FloatField()),
                ('estado', models.CharField(choices=[('Emitido', 'Emitido'), ('Anulado', 'Anulado')], max_length=12, verbose_name='Condición de venta')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
            },
        ),
    ]
