# Generated by Django 3.1.13 on 2022-11-18 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cobros', '0005_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='numero_documento',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='sub_nro_factura3',
            field=models.IntegerField(),
        ),
    ]
