# Generated by Django 3.1.13 on 2022-11-18 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cobros', '0006_auto_20221117_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='condicion_venta',
            field=models.CharField(choices=[('Contado', 'Contado'), ('Credito', 'Credito')], default='Contado', max_length=12, verbose_name='Condición de venta'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='iva_10',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='iva_5',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='sub_nro_factura1',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='factura',
            name='sub_nro_factura2',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='factura',
            name='sub_nro_factura3',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='total_iva',
            field=models.FloatField(null=True),
        ),
    ]
