# Generated by Django 3.1.13 on 2022-11-22 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cobros', '0008_auto_20221122_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallefactura',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='exentas',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='gravado_10_porc',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='gravado_5_porc',
            field=models.IntegerField(null=True),
        ),
    ]
