# Generated by Django 3.1.13 on 2022-11-22 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cobros', '0009_auto_20221122_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallefactura',
            name='descripcion',
            field=models.CharField(max_length=40),
        ),
    ]
