# Generated by Django 3.1.13 on 2022-11-29 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cobros', '0011_caja_detallecaja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='fecha_cierre',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='caja',
            name='hora_cierre',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='caja',
            name='monto_cierre',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
