# Generated by Django 3.1.13 on 2022-12-06 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cobros', '0012_auto_20221129_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='saldo_anterior',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
