# Generated by Django 3.1.13 on 2022-12-08 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cobros', '0013_caja_saldo_anterior'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='cobro_contado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion_cobros.cobrocontado'),
        ),
        migrations.AlterField(
            model_name='cobrocontado',
            name='fecha',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='cobrocontado',
            name='monto_total',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cobrocontado',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='numero de documento'),
        ),
        migrations.AlterField(
            model_name='cobrocontado',
            name='razon_social',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre o razón social'),
        ),
    ]
