# Generated by Django 3.1.13 on 2022-12-08 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cobros', '0014_auto_20221208_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecobrotratamiento',
            name='cobro_contado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion_cobros.cobrocontado'),
        ),
    ]
