# Generated by Django 3.1.13 on 2022-12-08 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cobros', '0017_remove_detallecobrotratamiento_detalle_cobro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DetalleCobroContado',
        ),
    ]
