# Generated by Django 3.1.13 on 2022-12-08 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cobros', '0019_auto_20221208_1729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallecaja',
            old_name='id_comprobante',
            new_name='comprobante_cobro',
        ),
    ]
