# Generated by Django 3.1.13 on 2022-12-17 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cobros', '0023_auto_20221216_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecaja',
            name='comprobante_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion_cobros.comprobantegasto'),
        ),
    ]
