# Generated by Django 3.1.13 on 2022-12-17 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cobros', '0024_auto_20221216_2214'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DetalleGasto',
        ),
    ]
