# Generated by Django 3.1.13 on 2022-12-17 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cobros', '0025_delete_detallegasto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprobantegasto',
            name='gasto',
        ),
    ]
