# Generated by Django 3.1.13 on 2022-12-23 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cobros', '0029_auto_20221218_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='nombre_mes',
            field=models.CharField(choices=[('Enero', 'Enero'), ('Febrero', 'Febrero'), ('Marzo', 'Marzo'), ('Abril', 'Abril'), ('Mayo', 'Mayo'), ('Junio', 'Junio'), ('Julio', 'Julio'), ('Agosto', 'Agosto'), ('Septiembre', 'Septiembre'), ('Octubre', 'Octubre'), ('Noviembre', 'Noviembre'), ('Diciembre', 'Diciembre')], default='', max_length=20, verbose_name='Condición de venta'),
        ),
    ]
