# Generated by Django 3.1.13 on 2022-12-22 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cobros', '0030_auto_20221221_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobrocontado',
            name='condicion_venta',
            field=models.CharField(choices=[('Contado', 'Contado'), ('Credito', 'Credito')], default='Contado', max_length=12, verbose_name='Condición de venta'),
        ),
        migrations.AddField(
            model_name='cobrocontado',
            name='direccion',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='cobrocontado',
            name='estado',
            field=models.CharField(choices=[('Emitido', 'Emitido'), ('Anulado', 'Anulado')], default='Emitido', max_length=12, verbose_name='Condición de venta'),
        ),
        migrations.AddField(
            model_name='cobrocontado',
            name='iva_10',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='cobrocontado',
            name='iva_5',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='cobrocontado',
            name='nro_factura',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='cobrocontado',
            name='sub_nro_factura1',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='cobrocontado',
            name='sub_nro_factura2',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='cobrocontado',
            name='sub_nro_factura3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cobrocontado',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cobrocontado',
            name='total_iva',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='cobrocontado',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
