# Generated by Django 3.1.13 on 2022-12-23 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cobros', '0030_factura_nombre_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='nombre_mes',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Mes'),
        ),
    ]
