# Generated by Django 3.1.13 on 2022-12-23 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cobros', '0031_auto_20221222_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='fecha_fin',
            field=models.DateField(null=True),
        ),
    ]
