# Generated by Django 3.1.13 on 2022-08-23 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_tratamiento', '0008_tratamientoinsumo_cantidad'),
        ('gestion_administrativo', '0056_auto_20220817_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id_hora', models.AutoField(primary_key=True, serialize=False)),
                ('hora', models.TimeField()),
                ('dias_atencion', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes')], max_length=100, null=True, verbose_name='Días de atención')),
            ],
            options={
                'verbose_name_plural': 'Horario',
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id_cita', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_paciente', models.CharField(max_length=40, null=True, verbose_name='Nombre del Paciente')),
                ('apellido_paciente', models.CharField(max_length=40, null=True, verbose_name='Apellido del Paciente')),
                ('fecha', models.DateField()),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('hora_atencion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion_agendamiento.horario', verbose_name='Hora de atencion')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_administrativo.paciente')),
                ('profesional', models.ForeignKey(max_length=45, on_delete=django.db.models.deletion.PROTECT, to='gestion_administrativo.especialidad', verbose_name='Profesional a elegir')),
                ('tratamiento_solicitado', models.ForeignKey(max_length=45, on_delete=django.db.models.deletion.PROTECT, to='gestion_tratamiento.tratamiento', verbose_name='Motivo de consulta')),
            ],
            options={
                'verbose_name_plural': 'Cita',
            },
        ),
    ]
