# Generated by Django 3.1.13 on 2022-08-24 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_administrativo', '0056_auto_20220817_1551'),
        ('gestion_agendamiento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='profesional',
            field=models.ForeignKey(max_length=45, on_delete=django.db.models.deletion.PROTECT, to='gestion_administrativo.especialistasalud', verbose_name='Profesional a elegir'),
        ),
    ]
