# Generated by Django 3.1.13 on 2022-08-25 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_agendamiento', '0002_auto_20220823_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.BooleanField(default=False, verbose_name='Estado'),
        ),
    ]
