# Generated by Django 3.1.13 on 2022-07-02 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_agendamiento', '0002_cita_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='nombre_paciente',
            field=models.CharField(default='default', max_length=40, verbose_name='Nombre del Paciente'),
            preserve_default=False,
        ),
    ]
