# Generated by Django 3.1.13 on 2022-07-13 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_agendamiento', '0003_cita_nombre_paciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='nombre_paciente',
            field=models.CharField(max_length=40, null=True, verbose_name='Nombre del Paciente'),
        ),
    ]
