# Generated by Django 3.1.13 on 2022-08-26 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_agendamiento', '0003_auto_20220825_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.BooleanField(default=False, verbose_name='Confirmar cita'),
        ),
    ]
