# Generated by Django 3.1.13 on 2022-07-13 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_tratamiento', '0006_delete_horario'),
        ('gestion_agendamiento', '0004_auto_20220712_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='tratamiento_solicitado',
            field=models.ForeignKey(max_length=45, on_delete=django.db.models.deletion.PROTECT, to='gestion_tratamiento.tratamiento', verbose_name='Motivo de consulta'),
        ),
    ]
