# Generated by Django 3.1.13 on 2022-09-16 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_administrativo', '0057_auto_20220823_2203'),
        ('gestion_agendamiento', '0004_auto_20220826_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='celular',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion_administrativo.persona'),
        ),
    ]
