# Generated by Django 3.1.13 on 2022-07-13 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_agendamiento', '0005_auto_20220712_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='apellido_paciente',
            field=models.CharField(max_length=40, null=True, verbose_name='Nombre del Paciente'),
        ),
    ]
