# Generated by Django 3.1.13 on 2022-09-30 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_agendamiento', '0006_auto_20220921_2322'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cita',
            options={'ordering': ['fecha'], 'verbose_name_plural': 'Cita'},
        ),
    ]
