# Generated by Django 3.1.13 on 2022-09-30 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_agendamiento', '0007_auto_20220930_1554'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cita',
            options={'ordering': ['nombre_paciente'], 'verbose_name_plural': 'Cita'},
        ),
    ]
