# Generated by Django 3.1.13 on 2022-08-18 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_agendamiento', '0008_cita_profesional'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id_hora', models.AutoField(primary_key=True, serialize=False)),
                ('hora', models.TimeField()),
                ('dias_atencion', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes')], max_length=100, null=True, verbose_name='Días de atención')),
            ],
            options={
                'verbose_name_plural': 'Horario',
            },
        ),
    ]
