# Generated by Django 3.1.13 on 2022-10-10 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_tratamiento', '0014_auto_20220930_1636'),
        ('gestion_agendamiento', '0009_auto_20220930_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='tratamiento_simple',
            field=models.CharField(choices=[('CONSULTA DE DIAGNOSTICO', 'CONSULTA DE DIAGNOSTICO'), ('CHEQUEO DE RUTINA', 'CHEQUEO DE RUTINA'), ('CONTROL Y SEGUIMIENTO DEL TRATAMIENTO', 'CONTROL Y SEGUIMIENTO DEL TRATAMIENTO'), ('ORTODONCIA', 'ORTODONCIA')], max_length=300, null=True, verbose_name='Motivo de la Consulta'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='tratamiento_solicitado',
            field=models.ForeignKey(max_length=45, on_delete=django.db.models.deletion.PROTECT, to='gestion_tratamiento.tratamiento', verbose_name='Tratamientos'),
        ),
    ]
