# Generated by Django 3.1.13 on 2022-10-18 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_agendamiento', '0012_auto_20221011_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='tratamiento_simple',
        ),
    ]
