# Generated by Django 3.1.13 on 2022-10-21 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_agendamiento', '0014_cita_tratamiento_simple'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='apellido_paciente',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='celular',
        ),
    ]
