# Generated by Django 3.1.13 on 2022-04-23 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agregar_mas', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cargo',
        ),
    ]
