# Generated by Django 3.1.13 on 2021-10-16 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('codigo_tratamiento', models.AutoField(primary_key=True, serialize=False, verbose_name='Código de tratamiento (*)')),
                ('nombre_tratamiento', models.CharField(max_length=40, verbose_name='nombre (*)')),
                ('descripcion_tratamiento', models.TextField(verbose_name='descripción (*)')),
                ('precio', models.IntegerField(verbose_name='precio (*)')),
            ],
            options={
                'verbose_name': 'tratamiento',
                'verbose_name_plural': 'tratamientos',
                'db_table': 'Tratamiento',
            },
        ),
    ]
