# Generated by Django 3.1.13 on 2022-05-23 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_tratamiento', '0003_auto_20220517_0841'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tratamiento',
            options={'ordering': ['nombre_tratamiento'], 'verbose_name': 'tratamiento', 'verbose_name_plural': 'tratamientos'},
        ),
    ]
