# Generated by Django 3.1.13 on 2022-06-30 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_tratamiento', '0005_horario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Horario',
        ),
    ]
