# Generated by Django 3.1.13 on 2022-07-14 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_tratamiento', '0007_auto_20220713_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='tratamientoinsumo',
            name='cantidad',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
