# Generated by Django 3.1.13 on 2022-09-05 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inventario_insumos', '0014_auto_20220818_1450'),
        ('gestion_tratamiento', '0009_auto_20220905_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='TratamientoInsumoAsignado',
            fields=[
                ('id_insumo_asig', models.AutoField(primary_key=True, serialize=False)),
                ('insumo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_inventario_insumos.insumo')),
                ('tratamiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_tratamiento.tratamiento')),
            ],
            options={
                'db_table': 'TratamientoInsumoAsignado',
            },
        ),
    ]
