# Generated by Django 3.1.13 on 2022-09-28 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inventario_insumos', '0014_auto_20220818_1450'),
        ('gestion_tratamiento', '0011_tratamiento_insumos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tratamiento',
            options={'ordering': ['nombre_tratamiento'], 'verbose_name': 'tratamiento', 'verbose_name_plural': 'tratamientos'},
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='insumos',
            field=models.ManyToManyField(blank=True, null=True, related_name='tratamiento_set', through='gestion_tratamiento.TratamientoInsumoAsignado', to='gestion_inventario_insumos.Insumo'),
        ),
    ]
