# Generated by Django 3.1.13 on 2022-09-30 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inventario_insumos', '0015_auto_20220930_1635'),
        ('gestion_tratamiento', '0013_tratamientoinsumoasignado_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tratamiento',
            name='insumos',
            field=models.ManyToManyField(blank=True, related_name='tratamiento_set', through='gestion_tratamiento.TratamientoInsumoAsignado', to='gestion_inventario_insumos.Insumo'),
        ),
    ]
