# Generated by Django 3.1.13 on 2022-10-28 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_tratamiento', '0015_tratamientocategoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tratamientocategoria',
            old_name='categoria_tratamiento',
            new_name='tratamiento',
        ),
        migrations.AlterField(
            model_name='tratamientocategoria',
            name='tipo_categoria',
            field=models.CharField(choices=[('Simple', 'Simple'), ('Complejo', 'Complejo')], default='Complejo', max_length=20),
        ),
    ]
