# Generated by Django 3.1.13 on 2022-10-20 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_tratamiento', '0016_auto_20221020_1050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tratamientocategoria',
            old_name='categoria_tratamiento',
            new_name='tratamiento',
        ),
    ]
