# Generated by Django 3.1.13 on 2022-06-29 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inventario_insumos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='descripción_insumo',
            field=models.TextField(max_length=500, verbose_name='Descripción ():'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='estado',
            field=models.CharField(blank=True, choices=[('Disponible', 'Disponible'), ('Intermedio', 'Intermedio'), ('En Falta', 'En Falta')], default='Disponible', help_text='Disponibilidad del Insumo', max_length=15),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='fecha_caducidad',
            field=models.DateField(verbose_name='Fecha de caducidad del insumo'),
        ),
    ]
