# Generated by Django 3.1.13 on 2022-06-30 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inventario_insumos', '0002_auto_20220629_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insumo',
            name='estado',
        ),
    ]
