# Generated by Django 3.1.13 on 2022-07-12 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inventario_insumos', '0003_remove_insumo_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='descripción_insumo',
            field=models.CharField(max_length=500, verbose_name='Descripción ():'),
        ),
    ]
