# Generated by Django 3.1.13 on 2022-07-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inventario_insumos', '0004_auto_20220712_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='descripción_insumo',
            field=models.TextField(max_length=500, verbose_name='Descripción (*):'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='nombre_insumo',
            field=models.CharField(max_length=100, verbose_name='Nombre (*):'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='precio',
            field=models.IntegerField(max_length=9, verbose_name='Precio (*):'),
        ),
    ]
