# Generated by Django 3.1.13 on 2022-07-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inventario_insumos', '0006_auto_20220712_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='fecha_caducidad',
            field=models.DateField(verbose_name='Fecha de nacimiento'),
        ),
    ]
