# Generated by Django 3.1.13 on 2022-07-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inventario_insumos', '0008_auto_20220712_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='cantidad_insumo',
            field=models.IntegerField(default=0, verbose_name='Cantidad (*)'),
        ),
    ]
