# Generated by Django 3.1.13 on 2022-07-14 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inventario_insumos', '0009_insumo_cantidad_insumo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='precio',
            field=models.IntegerField(verbose_name='Costo (*):'),
        ),
    ]
