# Generated by Django 3.1.13 on 2022-07-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inventario_insumos', '0010_auto_20220713_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='unidad',
            field=models.IntegerField(default=0, verbose_name='Cantidad (*)'),
        ),
    ]
