# Generated by Django 3.1.13 on 2022-07-18 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inventario_insumos', '0011_insumo_unidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='unidad',
            field=models.IntegerField(default=0, verbose_name='Unidad (*)'),
        ),
    ]
