# Generated by Django 3.1.13 on 2022-08-18 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inventario_insumos', '0013_auto_20220818_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='unidad',
            field=models.CharField(choices=[('Paquetes', 'Paquetes'), ('Cajas', 'Cajas'), ('Litros', 'Litros')], max_length=12, verbose_name='Unidad'),
        ),
    ]
