# Generated by Django 3.1.13 on 2022-10-08 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inventario_insumos', '0015_auto_20220930_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='unidad',
            field=models.CharField(choices=[('Paquete/s', 'Paquete/s'), ('Caja/s', 'Caja/s'), ('Litro/s', 'Litro/s')], max_length=12, verbose_name='Unidad de medida'),
        ),
    ]
