# Generated by Django 3.1.13 on 2022-10-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inventario_insumos', '0016_auto_20221007_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='precio',
            field=models.IntegerField(verbose_name='Costo Unitario (*):'),
        ),
    ]
