# Generated by Django 3.1.13 on 2022-10-24 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inventario_insumos', '0018_auto_20221014_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='stock_minimo',
            field=models.IntegerField(default=0, verbose_name='Stock Mínimo (*)'),
        ),
    ]
