# Generated by Django 3.1.13 on 2022-11-04 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inventario_insumos', '0019_auto_20221024_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='calculo_valor',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='stock_minimo',
            field=models.IntegerField(default=0, verbose_name='Stock mínimo (*)'),
        ),
    ]
