# Generated by Django 3.1.13 on 2022-11-05 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inventario_insumos', '0022_auto_20221105_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='ud_unitaria',
            field=models.CharField(choices=[('mg', 'ml'), ('ml', 'ml'), ('mm', 'mm'), ('ampollas', 'amp')], max_length=12, verbose_name='Ud. Unitaria'),
        ),
    ]
