# Generated by Django 3.1.13 on 2022-11-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inventario_insumos', '0023_auto_20221105_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='ud_unitaria',
            field=models.CharField(choices=[('mg', 'mg'), ('ml', 'ml'), ('mm', 'mm'), ('ampollas', 'amp')], max_length=12, verbose_name='Ud. Unitaria'),
        ),
    ]
