# Generated by Django 3.1.13 on 2022-11-11 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inventario_insumos', '0026_auto_20221107_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='existencia',
            field=models.CharField(blank=True, choices=[('Disponible', 'Disponible'), ('Intermedio', 'Intermedio'), ('En Falta', 'En Falta')], default='Disponible', help_text='Disponibilidad del Insumo', max_length=15),
        ),
    ]
