# Generated by Django 3.1.13 on 2021-10-30 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_historial_clinico', '__first__'),
        ('agregar_mas', '0001_initial'),
        ('gestion_tratamiento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('codigo_categoria', models.AutoField(primary_key=True, serialize=False, verbose_name='codigo')),
                ('detalle_tratamiento', models.CharField(max_length=40, verbose_name='detalle')),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('codigo_tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_tratamiento.tratamiento', verbose_name='Código de tratamiento')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'Categoria',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('nombre', models.CharField(max_length=40, verbose_name='Nombre (*)')),
                ('apellido', models.CharField(max_length=40, verbose_name='Apellido (*)')),
                ('numero_documento', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=40, verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=20, verbose_name='Telefono')),
                ('correo_electronico', models.CharField(max_length=35, verbose_name='Correo electrónico')),
                ('fecha_nacimiento', models.DateField(null=True, verbose_name='Fecha de nacimiento')),
                ('sexo', models.CharField(choices=[('Femenino', 'Femenino'), ('Masculino', 'Masculino')], max_length=12, verbose_name='Sexo')),
                ('es_funcionario', models.BooleanField(default=False, verbose_name='Funcionario')),
                ('es_personal_salud', models.BooleanField(default=False, verbose_name='Personal de salud')),
                ('es_paciente', models.BooleanField(default=False, verbose_name='Paciente')),
                ('es_proveedor', models.BooleanField(default=False, verbose_name='Proveedor')),
            ],
            options={
                'verbose_name_plural': 'Registro de personas',
                'db_table': 'Persona',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='EspecialistaSalud',
            fields=[
                ('numero_documento', models.OneToOneField(max_length=10, on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='gestion_administrativo.persona')),
                ('es_interno', models.BooleanField(blank=True, null=True, verbose_name='Es interno')),
                ('es_externo', models.BooleanField(blank=True, null=True, verbose_name='Es externo')),
            ],
            options={
                'verbose_name': 'Especialista de salud',
                'verbose_name_plural': 'Especialistas de salud',
                'db_table': 'EspecialistaSalud',
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('numero_documento', models.OneToOneField(max_length=10, on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='gestion_administrativo.persona')),
            ],
            options={
                'verbose_name_plural': 'Funcionarios',
                'db_table': 'Funcionario',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('numero_documento', models.OneToOneField(max_length=10, on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='gestion_administrativo.persona')),
                ('enfermedad_base', models.CharField(default='', max_length=60, verbose_name='Enfermedad de base (*)')),
                ('alergia', models.CharField(default='', max_length=60, verbose_name='Alergia (*)')),
                ('tolerancia_anestecia', models.BooleanField(default=False, verbose_name='Tolerancia a la anestecia')),
                ('frecuencia_higiene_bucal', models.CharField(default='', max_length=60, verbose_name='Frecuencia de higiene bucal (*)')),
                ('medicamento', models.CharField(default='', max_length=60, verbose_name='Medicamento/s (*)')),
                ('cirugias', models.BooleanField(default=False, verbose_name='Cirugías (*)')),
                ('caries', models.BooleanField(default=False, verbose_name='Caries (*)')),
                ('afeccion_cronica_familiar', models.CharField(default='', max_length=500, verbose_name='Afección crónica familiar (*)')),
                ('afecciones_graves', models.CharField(default='', max_length=500, verbose_name='Afecciones graves (*)')),
                ('grupo_sanguineo', models.CharField(default='', max_length=100, verbose_name='Grupo sanguíneo (*)')),
                ('numero_ficha', models.OneToOneField(default=0, on_delete=django.db.models.deletion.PROTECT, to='gestion_historial_clinico.historialclinico', verbose_name='Número de ficha')),
            ],
            options={
                'verbose_name': 'paciente',
                'verbose_name_plural': 'pacientes',
                'db_table': 'Paciente',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('numero_documento', models.OneToOneField(max_length=10, on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='gestion_administrativo.persona')),
            ],
            options={
                'verbose_name_plural': 'Proveedores',
                'db_table': 'Proveedor',
            },
        ),
        migrations.CreateModel(
            name='TratamientoRealizado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_tratamiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion_tratamiento.tratamiento')),
                ('numero_ficha', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion_historial_clinico.historialclinico', verbose_name='Número de ficha')),
                ('numero_documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion_administrativo.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='TrabajoRealizado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_servicio', models.BigIntegerField(null=True, verbose_name='Costo de servicio')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion_administrativo.categoria')),
                ('especialista_salud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion_administrativo.especialistasalud')),
            ],
            options={
                'verbose_name': 'Trabajo Realizado',
                'verbose_name_plural': 'Trabajos Realizados',
                'db_table': 'TrabajoRealizado',
            },
        ),
        migrations.CreateModel(
            name='PersonalInternoCargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salario', models.BigIntegerField(null=True)),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='agregar_mas.cargo')),
                ('personal_interno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion_administrativo.funcionario')),
            ],
            options={
                'verbose_name': 'Cargos de empleado',
                'db_table': 'PersonalInternoCargo',
            },
        ),
        migrations.AddField(
            model_name='funcionario',
            name='cargos',
            field=models.ManyToManyField(through='gestion_administrativo.PersonalInternoCargo', to='agregar_mas.Cargo'),
        ),
        migrations.AddField(
            model_name='especialistasalud',
            name='TrabajosRealizados',
            field=models.ManyToManyField(through='gestion_administrativo.TrabajoRealizado', to='gestion_administrativo.Categoria'),
        ),
    ]
