# Generated by Django 3.1.13 on 2022-03-11 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_administrativo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='correo_electronico',
            field=models.EmailField(max_length=35, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='numero_documento',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Cedula de identidad'),
        ),
    ]
