# Generated by Django 3.1.13 on 2022-03-12 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_administrativo', '0002_auto_20220310_2326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='numero_ficha',
        ),
    ]
