# Generated by Django 3.1.13 on 2022-03-12 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_administrativo', '0004_auto_20220311_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='tolerancia_anestecia',
            field=models.BooleanField(null=True, verbose_name='Tolerancia a la anestecia'),
        ),
    ]
