# Generated by Django 3.1.13 on 2022-04-04 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_administrativo', '0005_auto_20220312_0001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('cargo', models.CharField(max_length=25, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
            },
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cargos',
            field=models.ManyToManyField(through='gestion_administrativo.PersonalInternoCargo', to='gestion_administrativo.Cargo'),
        ),
        migrations.AlterField(
            model_name='personalinternocargo',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion_administrativo.cargo'),
        ),
    ]
