# Generated by Django 3.1.13 on 2022-04-22 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_administrativo', '0006_auto_20220404_1422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='tolerancia_anestecia',
            new_name='intolerancia_anestecia',
        ),
    ]
