# Generated by Django 3.1.13 on 2022-04-23 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_administrativo', '0008_auto_20220422_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='alergia',
            field=models.TextField(max_length=500, null=True, verbose_name='Alergia (*)'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='enfermedad_base',
            field=models.TextField(max_length=500, null=True, verbose_name='Enfermedad de base (*)'),
        ),
    ]
