# Generated by Django 3.1.13 on 2022-04-23 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_administrativo', '0009_auto_20220422_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='cargos',
        ),
        migrations.DeleteModel(
            name='PersonalInternoCargo',
        ),
    ]
