# Generated by Django 3.1.13 on 2022-04-27 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_administrativo', '0011_auto_20220422_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='id_funcionario',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
