# Generated by Django 3.1.13 on 2022-04-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_administrativo', '0013_remove_funcionario_id_funcionario'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='id_funcionario',
            field=models.IntegerField(default=0),
        ),
    ]
