# Generated by Django 3.1.13 on 2022-04-27 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_administrativo', '0014_funcionario_id_funcionario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='id_funcionario',
        ),
    ]
