# Generated by Django 3.1.13 on 2022-04-27 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_administrativo', '0015_remove_funcionario_id_funcionario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionariocargo',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='funcionariocargo',
            name='funcionario',
        ),
        migrations.DeleteModel(
            name='Funcionario',
        ),
        migrations.DeleteModel(
            name='FuncionarioCargo',
        ),
    ]
