# Generated by Django 3.1.13 on 2022-04-27 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_administrativo', '0016_auto_20220427_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id_funcionario', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Funcionarios',
                'db_table': 'Funcionario',
            },
        ),
        migrations.CreateModel(
            name='FuncionarioCargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salario', models.BigIntegerField(null=True)),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion_administrativo.cargo')),
                ('funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion_administrativo.funcionario')),
            ],
            options={
                'verbose_name': 'Cargos de empleado',
                'db_table': 'FuncionarioCargo',
            },
        ),
        migrations.AddField(
            model_name='funcionario',
            name='cargos',
            field=models.ManyToManyField(through='gestion_administrativo.FuncionarioCargo', to='gestion_administrativo.Cargo'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='numero_documento',
            field=models.OneToOneField(max_length=10, on_delete=django.db.models.deletion.PROTECT, to='gestion_administrativo.persona'),
        ),
    ]
