# Generated by Django 3.1.13 on 2022-04-28 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_administrativo', '0017_auto_20220427_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajorealizado',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='trabajorealizado',
            name='especialista_salud',
        ),
        migrations.DeleteModel(
            name='EspecialistaSalud',
        ),
        migrations.DeleteModel(
            name='TrabajoRealizado',
        ),
    ]
