# Generated by Django 3.1.13 on 2022-04-28 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_administrativo', '0018_auto_20220427_2229'),
    ]

    operations = [
        migrations.CreateModel(
            name='EspecialistaSalud',
            fields=[
                ('id_especialista_salud', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Especialista de salud',
                'verbose_name_plural': 'Especialistas de salud',
                'db_table': 'EspecialistaSalud',
            },
        ),
        migrations.CreateModel(
            name='TrabajoRealizado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_servicio', models.BigIntegerField(null=True, verbose_name='Costo de servicio')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion_administrativo.categoria')),
                ('especialista_salud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion_administrativo.especialistasalud')),
            ],
            options={
                'verbose_name': 'Trabajo Realizado',
                'verbose_name_plural': 'Trabajos Realizados',
                'db_table': 'TrabajoRealizado',
            },
        ),
        migrations.AddField(
            model_name='especialistasalud',
            name='TrabajosRealizados',
            field=models.ManyToManyField(through='gestion_administrativo.TrabajoRealizado', to='gestion_administrativo.Categoria'),
        ),
        migrations.AddField(
            model_name='especialistasalud',
            name='numero_documento',
            field=models.OneToOneField(max_length=10, on_delete=django.db.models.deletion.PROTECT, to='gestion_administrativo.persona'),
        ),
    ]
