# Generated by Django 3.1.13 on 2022-04-28 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_administrativo', '0019_auto_20220427_2234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='especialistasalud',
            old_name='TrabajosRealizados',
            new_name='trabajos_realizados',
        ),
    ]
