# Generated by Django 3.1.13 on 2022-04-29 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_administrativo', '0020_auto_20220427_2253'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Proveedor',
        ),
    ]
