# Generated by Django 3.1.13 on 2022-04-29 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_administrativo', '0021_delete_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Código')),
                ('nombre', models.CharField(max_length=30)),
                ('precio', models.PositiveIntegerField(blank=True, max_length=10, null=True)),
                ('fecha_vencimiento', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Insumos',
                'db_table': 'Insumo',
            },
        ),
        migrations.CreateModel(
            name='InsumosProveidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion_administrativo.insumo')),
            ],
            options={
                'verbose_name_plural': 'Insumos proveidos',
                'db_table': 'InsumoProveido',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('ruc', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('direccion', models.CharField(max_length=50, verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('correo_electronico', models.EmailField(max_length=35, verbose_name='Correo electrónico')),
                ('producto', models.ManyToManyField(through='gestion_administrativo.InsumosProveidos', to='gestion_administrativo.Insumo')),
            ],
            options={
                'verbose_name_plural': 'Proveedores',
                'db_table': 'Proveedor',
            },
        ),
        migrations.AddField(
            model_name='insumosproveidos',
            name='ruc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion_administrativo.proveedor'),
        ),
    ]
