# Generated by Django 3.1.13 on 2022-05-05 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_tratamiento', '0001_initial'),
        ('gestion_administrativo', '0023_auto_20220503_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='codigo_tratamiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_tratamiento.tratamiento', verbose_name='Código de tratamiento'),
        ),
    ]
