# Generated by Django 3.1.13 on 2022-05-05 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_tratamiento', '0001_initial'),
        ('gestion_administrativo', '0024_auto_20220505_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tratamientorealizado',
            name='codigo_tratamiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_tratamiento.tratamiento'),
        ),
        migrations.AlterField(
            model_name='tratamientorealizado',
            name='numero_documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_administrativo.paciente'),
        ),
    ]
