# Generated by Django 3.1.13 on 2022-05-09 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_administrativo', '0028_auto_20220505_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insumosproveidos',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='insumosproveidos',
            name='ruc',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='producto',
        ),
        migrations.DeleteModel(
            name='Insumo',
        ),
        migrations.DeleteModel(
            name='InsumosProveidos',
        ),
    ]
