# Generated by Django 3.1.13 on 2022-05-09 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_administrativo', '0029_auto_20220509_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='es_funcionario',
            field=models.BooleanField(default=False, verbose_name='Funcionario'),
        ),
        migrations.AddField(
            model_name='persona',
            name='es_paciente',
            field=models.BooleanField(default=False, verbose_name='Paciente'),
        ),
        migrations.AddField(
            model_name='persona',
            name='es_personal_salud',
            field=models.BooleanField(default=False, verbose_name='Personal de salud'),
        ),
        migrations.AddField(
            model_name='persona',
            name='es_proveedor',
            field=models.BooleanField(default=False, verbose_name='Proveedor'),
        ),
    ]
