# Generated by Django 3.1.13 on 2022-05-09 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_administrativo', '0030_auto_20220509_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='es_proveedor',
        ),
    ]
