# Generated by Django 3.1.13 on 2022-05-11 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_administrativo', '0031_remove_persona_es_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='frecuencia_higiene_bucal',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
