# Generated by Django 3.1.13 on 2022-05-13 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_administrativo', '0033_auto_20220513_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmaco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_farmaco', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='paciente',
            options={'ordering': ['numero_documento'], 'verbose_name': 'paciente', 'verbose_name_plural': 'pacientes'},
        ),
        migrations.AlterModelOptions(
            name='persona',
            options={'ordering': ['nombre'], 'verbose_name_plural': 'Registro de personas'},
        ),
        migrations.RemoveField(
            model_name='funcionariocargo',
            name='salario',
        ),
        migrations.AddField(
            model_name='cargo',
            name='salario',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
