# Generated by Django 3.1.13 on 2022-05-13 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_administrativo', '0034_auto_20220513_1619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cargo',
            old_name='cargo',
            new_name='nombre',
        ),
    ]
