# Generated by Django 3.1.13 on 2022-05-14 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_administrativo', '0035_auto_20220513_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionariocargo',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_administrativo.cargo'),
        ),
        migrations.AlterField(
            model_name='funcionariocargo',
            name='funcionario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_administrativo.funcionario'),
        ),
    ]
