# Generated by Django 3.1.13 on 2022-05-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_administrativo', '0036_auto_20220514_1201'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Farmaco',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='digito_verificador',
            field=models.PositiveIntegerField(null=True, verbose_name='Digito verificador'),
        ),
    ]
