# Generated by Django 3.1.13 on 2022-05-19 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_administrativo', '0037_auto_20220514_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='tolerancia_anestecia',
            field=models.BooleanField(null=True, verbose_name='¿Es tolerante al uso de Anestecia?'),
        ),
    ]
