# Generated by Django 3.1.13 on 2022-05-26 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_administrativo', '0038_auto_20220519_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cargos',
            field=models.ManyToManyField(related_name='funcionario_set', through='gestion_administrativo.FuncionarioCargo', to='gestion_administrativo.Cargo'),
        ),
    ]
