# Generated by Django 3.1.13 on 2022-05-31 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_tratamiento', '0004_auto_20220523_1511'),
        ('gestion_administrativo', '0040_auto_20220530_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='PacienteTratamientoAsignado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tratamiento', models.ManyToManyField(blank=True, to='gestion_tratamiento.Tratamiento')),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_administrativo.paciente')),
            ],
            options={
                'verbose_name': 'Tratamietos del Paciente',
                'db_table': 'PacienteTratamientoAsignado',
            },
        ),
    ]
