# Generated by Django 3.1.13 on 2022-06-07 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_tratamiento', '0004_auto_20220523_1511'),
        ('gestion_administrativo', '0041_pacientetratamientoasignado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientetratamientoasignado',
            name='nombre_tratamiento',
            field=models.ManyToManyField(blank=True, to='gestion_tratamiento.Tratamiento', verbose_name='Nombre de los tratamientos'),
        ),
    ]
