# Generated by Django 3.1.13 on 2022-06-12 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_administrativo', '0042_auto_20220607_1707'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pacientetratamientoasignado',
            options={'verbose_name': 'Tratamientos del Paciente'},
        ),
        migrations.AlterField(
            model_name='persona',
            name='fecha_nacimiento',
            field=models.DateField(default=1, verbose_name='Fecha de nacimiento'),
            preserve_default=False,
        ),
    ]
