# Generated by Django 3.1.13 on 2022-06-21 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_tratamiento', '0004_auto_20220523_1511'),
        ('gestion_administrativo', '0043_auto_20220612_1913'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pacientetratamientoasignado',
            options={'verbose_name': 'Tratamietos del Paciente'},
        ),
        migrations.RemoveField(
            model_name='pacientetratamientoasignado',
            name='nombre_tratamiento',
        ),
        migrations.AddField(
            model_name='paciente',
            name='tratamientos',
            field=models.ManyToManyField(related_name='paciente_set', through='gestion_administrativo.PacienteTratamientoAsignado', to='gestion_tratamiento.Tratamiento'),
        ),
        migrations.AddField(
            model_name='pacientetratamientoasignado',
            name='tratamiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_tratamiento.tratamiento', verbose_name='Tratamientos ConsulDent'),
        ),
    ]
