# Generated by Django 3.1.13 on 2022-06-11 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_administrativo', '0043_auto_20220609_1028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pacientetratamientoasignado',
            options={'verbose_name': 'Tratamientos del Paciente'},
        ),
    ]
