# Generated by Django 3.1.13 on 2022-06-29 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_administrativo', '0043_auto_20220624_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especialistasalud',
            name='trabajos_realizados',
        ),
        migrations.AlterField(
            model_name='paciente',
            name='alergia',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Alergia (*)'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='enfermedad_base',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Enfermedad de base (*)'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='medicamento',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Medicamento/s (*)'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='tolerancia_anestecia',
            field=models.BooleanField(blank=True, null=True, verbose_name='¿Es tolerante al uso de Anestecia?'),
        ),
    ]
