# Generated by Django 3.1.13 on 2022-07-14 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_administrativo', '0044_auto_20220701_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajorealizado',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='trabajorealizado',
            name='especialista_salud',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='TrabajoRealizado',
        ),
    ]
