# Generated by Django 3.1.13 on 2022-06-21 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_administrativo', '0044_auto_20220620_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especialistaespecialidades',
            name='especialidad',
        ),
        migrations.RemoveField(
            model_name='especialistaespecialidades',
            name='especialista_salud',
        ),
        migrations.RemoveField(
            model_name='especialistasalud',
            name='especialidades',
        ),
        migrations.DeleteModel(
            name='Especialidad',
        ),
        migrations.DeleteModel(
            name='EspecialistaEspecialidades',
        ),
    ]
