# Generated by Django 3.1.13 on 2022-06-21 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_administrativo', '0045_auto_20220620_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('nombre', models.CharField(max_length=25, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Especialidad',
                'verbose_name_plural': 'Especialidades',
                'db_table': 'Especialidad',
            },
        ),
        migrations.CreateModel(
            name='EspecialistaEspecialidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion_administrativo.especialidad')),
                ('especialista_salud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion_administrativo.especialistasalud')),
            ],
            options={
                'verbose_name': 'Especialdad de especialista',
                'verbose_name_plural': 'Especialidades de especialistas',
                'db_table': 'EspecialistaEspecialidades',
            },
        ),
        migrations.AddField(
            model_name='especialistasalud',
            name='especialidades',
            field=models.ManyToManyField(related_name='especialista_set', through='gestion_administrativo.EspecialistaEspecialidades', to='gestion_administrativo.Especialidad'),
        ),
    ]
