# Generated by Django 3.1.13 on 2022-06-24 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_administrativo', '0045_auto_20220623_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especialistasalud',
            name='trabajos_realizados',
        ),
    ]
