# Generated by Django 3.1.13 on 2022-08-01 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_administrativo', '0045_auto_20220713_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialistasalud',
            name='especialidades',
            field=models.ManyToManyField(related_name='especialista_set', through='gestion_administrativo.EspecialistaEspecialidades', to='gestion_administrativo.Especialidad'),
        ),
    ]
