# Generated by Django 3.1.13 on 2022-08-01 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_administrativo', '0046_auto_20220801_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialistasalud',
            name='especialidades',
            field=models.ManyToManyField(blank=True, related_name='especialista_set', through='gestion_administrativo.EspecialistaEspecialidades', to='gestion_administrativo.Especialidad'),
        ),
    ]
