# Generated by Django 3.1.13 on 2022-06-21 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_administrativo', '0046_auto_20220620_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cargos',
            field=models.ManyToManyField(blank=True, null=True, related_name='funcionario_set', through='gestion_administrativo.FuncionarioCargo', to='gestion_administrativo.Cargo'),
        ),
    ]
