# Generated by Django 3.1.13 on 2022-08-01 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_administrativo', '0047_auto_20220801_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cargos',
            field=models.ManyToManyField(blank=True, related_name='funcionario_set', through='gestion_administrativo.FuncionarioCargo', to='gestion_administrativo.Cargo'),
        ),
    ]
