# Generated by Django 3.1.13 on 2022-06-21 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_administrativo', '0047_auto_20220621_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialistasalud',
            name='especialidades',
            field=models.ManyToManyField(blank=True, null=True, related_name='especialista_set', through='gestion_administrativo.EspecialistaEspecialidades', to='gestion_administrativo.Especialidad'),
        ),
    ]
