# Generated by Django 3.1.13 on 2022-08-02 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_administrativo', '0048_auto_20220801_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientetratamientoasignado',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Realizado', 'Realizado')], default='Pendiente', max_length=12),
        ),
    ]
