# Generated by Django 3.1.13 on 2022-08-06 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_administrativo', '0049_pacientetratamientoasignado_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientetratamientoasignado',
            name='id_tratamiento',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pacientetratamientoasignado',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Realizado', 'Realizado'), ('Confirmado', 'Confirmado')], default='Pendiente', max_length=12),
        ),
    ]
