# Generated by Django 3.1.13 on 2022-06-21 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_administrativo', '0050_auto_20220621_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='especialidad',
            old_name='id_especialista',
            new_name='id_especialidad',
        ),
    ]
