# Generated by Django 3.1.13 on 2022-08-06 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_administrativo', '0050_auto_20220805_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientetratamientoasignado',
            name='id_tratamiento',
            field=models.IntegerField(),
        ),
    ]
