# Generated by Django 3.1.13 on 2022-08-10 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_administrativo', '0050_auto_20220809_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacientetratamientoasignado',
            name='id',
        ),
        migrations.AlterField(
            model_name='pacientetratamientoasignado',
            name='id_tratamiento_asig',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
