# Generated by Django 3.1.13 on 2022-08-06 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_administrativo', '0051_auto_20220805_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacientetratamientoasignado',
            name='id',
        ),
        migrations.AlterField(
            model_name='pacientetratamientoasignado',
            name='id_tratamiento',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
