# Generated by Django 3.1.13 on 2022-08-11 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_administrativo', '0051_auto_20220809_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='id_historial_clinico',
        ),
    ]
