# Generated by Django 3.1.13 on 2022-08-06 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_administrativo', '0052_auto_20220805_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientetratamientoasignado',
            name='id_tratamiento',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
