# Generated by Django 3.1.13 on 2022-08-06 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_historial_clinico', '0001_initial'),
        ('gestion_administrativo', '0053_auto_20220806_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='id_historial_clinico',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='gestion_historial_clinico.historialclinico'),
        ),
    ]
