# Generated by Django 3.1.13 on 2022-08-11 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_administrativo', '0053_auto_20220810_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tratamientoconfirmado',
            name='estado',
            field=models.CharField(choices=[('Realizado', 'Realizado'), ('Confirmado', 'Confirmado')], default='Confirmado', max_length=12),
        ),
    ]
