# Generated by Django 3.1.13 on 2022-08-06 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_historial_clinico', '0002_auto_20220806_1241'),
        ('gestion_administrativo', '0054_paciente_id_historial_clinico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='id_historial_clinico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion_historial_clinico.historialclinico'),
        ),
    ]
