# Generated by Django 3.1.13 on 2022-08-17 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_administrativo', '0054_auto_20220811_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionariocargo',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion_administrativo.cargo'),
        ),
    ]
