# Generated by Django 3.1.13 on 2022-08-06 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_administrativo', '0055_auto_20220806_1248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pacientetratamientoasignado',
            old_name='id_tratamiento',
            new_name='id_tratamiento_asig',
        ),
    ]
