# Generated by Django 3.1.13 on 2022-08-17 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_administrativo', '0055_auto_20220817_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialistaespecialidades',
            name='especialista_salud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_administrativo.especialistasalud'),
        ),
    ]
