# Generated by Django 3.1.13 on 2022-08-24 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_administrativo', '0056_auto_20220817_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialistaespecialidades',
            name='especialidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_administrativo.especialidad'),
        ),
    ]
