# Generated by Django 3.1.13 on 2022-10-06 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_administrativo', '0057_auto_20220823_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientetratamientoasignado',
            name='estado',
            field=models.CharField(choices=[('Asignado', 'Asignado'), ('Confirmado', 'Confirmado')], default='Asignado', max_length=10),
        ),
    ]
