# Generated by Django 3.1.13 on 2022-10-06 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_administrativo', '0058_pacientetratamientoasignado_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientetratamientoasignado',
            name='estado',
            field=models.CharField(choices=[('Asignado', 'Asignado'), ('Agendado', 'Agendado')], default='Agendado', max_length=10),
        ),
    ]
