# Generated by Django 3.1.13 on 2022-10-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_administrativo', '0059_auto_20221006_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientetratamientoasignado',
            name='estado',
            field=models.CharField(choices=[('Asignado', 'Asignado'), ('Agendado', 'Agendado')], default='Asignado', max_length=10),
        ),
    ]
