# Generated by Django 3.1.13 on 2022-10-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_administrativo', '0062_remove_pacientetratamientoasignado_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tratamientoconfirmado',
            name='estado',
            field=models.CharField(choices=[('Realizado', 'Realizado'), ('Confirmado', 'Confirmado'), ('Agendado', 'Agendado')], default='Agendado', max_length=12),
        ),
    ]
