# Generated by Django 3.1.13 on 2022-10-11 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_administrativo', '0063_auto_20221010_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tratamientoconfirmado',
            name='estado',
            field=models.CharField(choices=[('Realizado', 'Realizado'), ('Confirmado', 'Confirmado'), ('Agendado', 'Agendado')], default='Pendiente', max_length=12),
        ),
    ]
