# Generated by Django 3.1.13 on 2022-10-22 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_administrativo', '0065_auto_20221011_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='tratamientoconfirmado',
            name='id_cita',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
