# Generated by Django 3.1.13 on 2022-10-26 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_administrativo', '0066_tratamientoconfirmado_id_cita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tratamientoconfirmado',
            name='id_cita',
            field=models.IntegerField(null=True),
        ),
    ]
