# Generated by Django 3.1.13 on 2022-10-26 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_administrativo', '0067_auto_20221025_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tratamientoconfirmado',
            name='id_cita',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
