# Generated by Django 3.1.13 on 2022-10-31 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_administrativo', '0069_auto_20221031_1324'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Servicio',
        ),
    ]
