# Generated by Django 3.1.13 on 2022-11-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_administrativo', '0071_auto_20221031_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(max_length=40)),
                ('direccion', models.CharField(max_length=200, null=True, verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=20, null=True, verbose_name='Teléfono')),
                ('correo_electronico', models.EmailField(max_length=35, verbose_name='Correo electrónico')),
                ('ruc', models.CharField(max_length=12, null=True)),
                ('timbrado', models.IntegerField()),
                ('f_inicio_vigencia', models.DateField(verbose_name='Fecha Inicio Vigencia')),
                ('f_fin_vigencia', models.DateField(verbose_name='Fecha Fin Vigencia')),
            ],
            options={
                'verbose_name_plural': 'Empresa',
                'db_table': 'Empresa',
            },
        ),
    ]
