# Generated by Django 3.1.13 on 2022-03-31 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
       # ('auth', '0017_auto_20220326_1942'),
        ('gestion_administrativo', '0005_auto_20220312_0001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('usuario', models.CharField(help_text='  ✏️ Ejemplo @jperez', max_length=15, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Es Activo')),
                ('is_staff', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False, verbose_name='Es Administrador')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('numero_documento', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_administrativo.persona', unique=True)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuario',
                'ordering': ['usuario'],
            },
        ),
    ]
