# Generated by Django 3.1.13 on 2022-04-23 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_administrativo', '0010_auto_20220422_2030'),
        ('webapp', '0002_auto_20220420_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='numero_documento',
            field=models.OneToOneField(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_administrativo.persona'),
        ),
    ]
