# Generated by Django 3.1.13 on 2022-05-23 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_administrativo', '0038_auto_20220519_0948'),
        ('webapp', '0003_auto_20220422_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='numero_documento',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestion_administrativo.persona'),
        ),
    ]
