# Generated by Django 3.1.13 on 2022-11-03 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        #('auth', '0016_auto_20211029_2321'),
        ('webapp', '0007_auto_20221031_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
    ]
